export default {
  primaryLighter: "#faac54" /* MISSING */,
  primaryLight: "#8fff8f",
  primary: "#5acf5f",
  primaryDark: "#189d31",
  primaryDarker: "#623b0c" /* MISSING */,
  secondary: "#9b8579",
  secondaryDark: "#6c584d",
  background: "#F0F0F7",
  cardBackgound: "#FFF",
  materialBackground: "#E1E2E1",
  resetColor: "#3F3F41",
  titleInPrimary: "#FFFFFF",
  textInPrimary: "#E6E6F0",
  textTitle: "#cf7711",
  textComplement: "#75727e",
  textBase: "#6A6180",
  lineInWhite: "#afafb8",
  inputBackground: "#F8F8FC",
  buttonText: "#FFFFFF",
  boxBase: "#FFFFFF",
  boxFooter: "#FAFAFC",
  smallInfo: "#C1BCCC",
};
